version: '2.25.0'

networks:
  backend:
    driver: bridge
    
services:
  prov-on-api:
    container_name: prov-on-api
    build: ./prov-on
    ports:
      - "4002:8080"
    networks:
      - backend
  prov-qc-api:
    container_name: prov-qc-api
    build: ./prov-qc
    ports:
      - "4001:8080"
    networks:
      - backend  
  gateway:
    container_name: fed-gateway
    build: ./federated-gateway
    ports:
      - "4000:4000"
    environment:
      QC_URL: http://prov-qc-api:8080
      ON_URL: http://prov-on-api:8080
    networks:
      - backend      
    depends_on:
      - "prov-on-api"
      - "prov-qc-api"