prov-on subgraph: {
  shape: circle
  style: {
    stroke: green
  }
  Review: {
    shape: circle
    id: id
    id.shape: circle
    rating: rating
    rating.shape: circle
    content: content
    content.shape: circle
    game: Game
    game.shape: circle
    author: Author
    author.shape: circle
  }
}

prov-qc subgraph: {
  shape: circle
  style: {
    stroke: green
  }
  Game: {
    shape: circle
    id: id
    id.shape: circle
    title: title
    title.shape: circle
    platform: "platform"
    platform.shape: circle
    platform.style.multiple: true
    reviews: "Reviews"
    reviews.shape: circle
    reviews.style.multiple: true
  }
  Author: {
    shape: circle
    id: id
    id.shape: circle
    name: name
    name.shape: circle
    verified: verified
    verified.shape: circle
    reviews: "Reviews"
    reviews.shape: circle
    reviews.style.multiple: true
  }
}

prov-on subgraph.Review.game -> prov-qc subgraph.Game
prov-on subgraph.Review.author -> prov-qc subgraph.Author

prov-qc subgraph.Game.reviews -> prov-on subgraph.Review
prov-qc subgraph.Author.reviews -> prov-on subgraph.Review
